version: 2
jobs:
  test:
    macos:
      xcode: "8.3.3"
    steps:
      run:
        - npm install -g react-native-cli
        - npm install -g detox-cli
        - detox build --configuration ios.sim.release
        - detox test --configuration ios.sim.release --cleanup
